name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph
  VCPKG_DEFAULT_TRIPLET: x64-mingw-static
  DEBUG: 'false'
  RESTRICT_SUFFIX: ${{ vars.RESTRICT && '_RESTRICT' || '' }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Checkout repository code
        uses: actions/checkout@v6
      - name: Install MinGW
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Set up vcpkg and install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "f7423ee180c4b7f40d43402c2feb3859161ef625"
          runVcpkgInstall: true
      - name: Show vcpkg install layout
        run: |
          echo "PWD=$(pwd)"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "VCPKG_ROOT=$VCPKG_ROOT"
          find "$GITHUB_WORKSPACE" -type f -name zlib.h -print
          find "$GITHUB_WORKSPACE" -maxdepth 3 -type d -name "vcpkg_installed" -print
          VCPKG_INSTALLED_DIR=$(find "$GITHUB_WORKSPACE" -type f -name zlib.h -print -quit | sed 's#/include/zlib.h##')
          echo "VCPKG_INSTALLED_DIR=$VCPKG_INSTALLED_DIR" >> "$GITHUB_ENV"
          echo "Found vcpkg installed dir: $VCPKG_INSTALLED_DIR"
          echo "VCPKG_INSTALLED_DIR=$VCPKG_INSTALLED_DIR"
          find "$VCPKG_INSTALLED_DIR/lib" -maxdepth 1 -type f -print
      - name: Build Windows test executable
        run: |
          x86_64-w64-mingw32-gcc simpleapp.c \
            -I"$VCPKG_INSTALLED_DIR/include" \
            -L"$VCPKG_INSTALLED_DIR/lib" \
            -l:libzlib.a \
            -o simpleapp.exe
      - name: Setup SM_CLIENT_CERT_FILE from base64 secret data
        run: |
          export SM_CLIENT_CERT_FILE=${RUNNER_TEMP}/sm_client_cert.p12
          echo "${{ secrets.SM_CLIENT_CERT_FILE_B64 }}" | base64 --decode > ${SM_CLIENT_CERT_FILE}
          echo "SM_CLIENT_CERT_FILE=${SM_CLIENT_CERT_FILE}" >> "$GITHUB_ENV"
        shell: bash
      - name: Verify SM client certificate file
        # DEBUG
        if: ${{ env.DEBUG == 'true' }}
        shell: bash
        run: |
          echo "SM_CLIENT_CERT_FILE=$SM_CLIENT_CERT_FILE"
          test -s "$SM_CLIENT_CERT_FILE"
          ls -l "$SM_CLIENT_CERT_FILE"
          openssl pkcs12 \
          -in "$SM_CLIENT_CERT_FILE" \
          -info \
          -noout \
          -passin pass:"${{ secrets[format('SM_CLIENT_CERT_PASSWORD{0}', env.SECRET_SUFFIX)] }}"
        # -passin pass:"${{ secrets.SM_CLIENT_CERT_PASSWORD }}"
      - name: Inspect client auth certificate metadata
        # DEBUG
        if: ${{ env.DEBUG == 'true' }}
        shell: bash
        run: |
          openssl pkcs12 \
          -in "$SM_CLIENT_CERT_FILE" \
          -clcerts \
          -nokeys \
          -passin pass:"${{ secrets.SM_CLIENT_CERT_PASSWORD }}" \
          | openssl x509 -noout -subject -issuer -dates -ext extendedKeyUsage
      - name: Sign simpleapp.exe with Software Trust Manager
        # It's easy to add STM signing to your current GHA workflow
        uses: digicert/code-signing-software-trust-action@v1.2.0
        with:
          simple-signing-mode: true
          input: simpleapp.exe
          keypair-alias: SA_ECDSA_PROD_KP
        env:
          SM_HOST: ${{ vars.SM_HOST }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_FILE: ${{ env.SM_CLIENT_CERT_FILE }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
      - name: Install signature verification tool and build cert store
        run: |
          sudo apt-get update
          sudo apt-get install -y osslsigncode
          
          printf '%s\n' "${{ secrets.STM_ROOT_CA_PEM }}" > stm-root-ca.pem
          printf '%s\n' "${{ secrets.STM_ICA_CA_PEM }}" > stm-ica-ca.pem
          printf '%s\n' "${{ secrets.STM_LEAF_CA_PEM }}" > stm-leaf-ca.pem
          
          openssl x509 -in stm-root-ca.pem -noout -subject -issuer -fingerprint -sha256
          openssl x509 -in stm-ica-ca.pem -noout -subject -issuer -fingerprint -sha256
          openssl x509 -in stm-leaf-ca.pem -noout -subject -issuer -fingerprint -sha256
      - name: Build STM CA bundle
        run: |
          cat stm-root-ca.pem stm-ica-ca.pem stm-leaf-ca.pem > stm-ca-bundle.pem
      - name: Inspect STM CA PEM files
        # DEBUG
        if: ${{ env.DEBUG == 'true' }}
        run: |
          echo "=== Root CA ==="
          openssl x509 -in stm-root-ca.pem -noout -subject -issuer -serial -fingerprint -sha256

          echo "=== ICA CA ==="
          openssl x509 -in stm-ica-ca.pem -noout -subject -issuer -serial -fingerprint -sha256
      - name: Verify signed EXE
        run: |
          osslsigncode verify \
            -CAfile stm-ca-bundle.pem \
            -in simpleapp.exe
      - run: echo "🍏 This job's status is ${{ job.status }}."
